AllCops:
 Exclude:
   - '*file'
   - metadata.rb

Metrics/LineLength:
 Max: 170

Metrics/AbcSize:
 Max: 30

Metrics/MethodLength:
 CountComments: false  # count full line comments?
 Max: 20

Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 2
